### ISSUE TITLE
Datasets for deribit back testing

### ISSUE THREAD

**Issue by ghost** [zelos-alpha/demeter#11]
Sorry for asking questions about unfinished work.

I'm trying to run some back testing of uniswap v3 pools with Deribit options.  And I'm using Tardis for historical datasets. With tardis i can get the datasets you're using while unit testing your code with all necessary fields. Problem is that this csv have different to yours internal structure. 

Example of my CSV:
`deribit_options_chain_2024-01-01_OPTIONS.csv`

```
exchange,symbol,timestamp,local_timestamp,type,strike_price,expiration,open_interest,last_price,bid_price,bid_amount,bid_iv,ask_price,ask_amount,ask_iv,mark_price,mark_iv,underlying_index,underlying_price,delta,gamma,vega,theta,rho
deribit,BTC-27SEP24-160000-P,1704067200027000,1704067200029840,put,160000,1727424000000000,0,2.45,,,,,,,2.4467,75.18,BTC-27SEP24,46593.7,-0.94333,0,45.67483,-6.35109,-1169.77956
deribit,BTC-27SEP24-140000-P,1704067200044000,1704067200047184,put,140000,1727424000000000,0,2.021,0.0001,1,,,,,2.0214,72.68,BTC-27SEP24,46593.7,-0.92595,0,56.21241,-7.55606,-1017.04325
deribit,BTC-27SEP24-95000-P,1704067200045000,1704067200047717,put,95000,1727424000000000,0,1.095,0.0002,1,,,,,1.0816,67.4,BTC-27SEP24,46593.7,-0.82594,0.00001,103.00981,-12.84055,-658.24389
```

From where do you get the historical dataset for testing deribit?
If you are also using Tardis, can you share the code that downloading that csv?

Thank you a lot, you created an amazing tool, you did a great job!

**Comment by 32ethers** [comment]
I just checked tardis, and I remembered why we cross out it:  400 u/month is too expensive for us.

Actually, we setup a small service to pull order books from deribit(https://docs.deribit.com/#public-get_order_book), it will collect all available order books on the hour. 

I was planning to share them regularly when the deribit module was officially released. However, due to being busy with some other tasks, the release was put on hold.

The Deribit module is now in a state of completed testing. Documentation and use cases still need to be added, and I also need to make some minor modifications.

If you need to use this module now, I can share the data on Dropbox or somewhere else.

**Comment by youbrain** [comment]
Yes, it would help me a lot if you shared the data. In any way convenient for you. Drop box — awesome.

**Comment by 32ethers** [comment]
I have uploaded them here, https://www.dropbox.com/scl/fo/kwk5kgiseu5rvccjscd0f/ANswtRLzpCxOc6cMTH0oRlE?rlkey=ai071f9695uz287lt8k0bci5e&dl=0

Just a heads-up, I've only gathered orderbooks on ETH. The data starts from 2023.3.16. and ends in 2024.2.22, Of course I have data after 2.22, but they are stored in MongoDB.  I can export them If you do need recent orderbooks.

And a bad news: some days in july and august  are missing due to server failure. you have to skip those days in backtesting

**Comment by 32ethers** [comment]
Hold on, I forgot I have updated column names, I have to re-export them.

**Comment by 32ethers** [comment]
> Hold on, I forgot I have updated column names, I have to re-export them. wait a moment

Done

I've re-exported the data, so the latest order book is now complete as well.
